# Generated by Django 5.1.6 on 2025-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
