# Generated by Django 5.1.6 on 2025-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name of File', db_comment='image name', max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Image Files')),
            ],
        ),
    ]
